//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.GroupModules = new HashSet<GroupModule>();
            this.ModuleRegistrations = new HashSet<ModuleRegistration>();
            this.ModuleTutors = new HashSet<ModuleTutor>();
            this.ModuleTypes = new HashSet<ModuleType>();
            this.Seminars = new HashSet<Seminar>();
        }
    
        public int ID { get; set; }
        public string SRSCode { get; set; }
        public string Name { get; set; }
        public int Credit { get; set; }
    
        public virtual ICollection<GroupModule> GroupModules { get; set; }
        public virtual ICollection<ModuleRegistration> ModuleRegistrations { get; set; }
        public virtual ICollection<ModuleTutor> ModuleTutors { get; set; }
        public virtual ICollection<ModuleType> ModuleTypes { get; set; }
        public virtual ICollection<Seminar> Seminars { get; set; }
    }
}
