//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleTutor
    {
        public int ModuleID { get; set; }
        public int TutorID { get; set; }
        public int TimeID { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Time Time { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
