//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.CourseRegistrations = new HashSet<CourseRegistration>();
            this.GroupAllocations = new HashSet<GroupAllocation>();
            this.LevelProgressions = new HashSet<LevelProgression>();
            this.ModuleRegistrations = new HashSet<ModuleRegistration>();
        }
    
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Password { get; set; }
        public string EmailPrefix { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<CourseRegistration> CourseRegistrations { get; set; }
        public virtual ICollection<GroupAllocation> GroupAllocations { get; set; }
        public virtual ICollection<LevelProgression> LevelProgressions { get; set; }
        public virtual ICollection<ModuleRegistration> ModuleRegistrations { get; set; }
    }
}
