//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public Tutor()
        {
            this.Attendances = new HashSet<Attendance>();
            this.ModuleTutors = new HashSet<ModuleTutor>();
            this.Seminars = new HashSet<Seminar>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Password { get; set; }
        public string EmailPrefix { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<ModuleTutor> ModuleTutors { get; set; }
        public virtual ICollection<Seminar> Seminars { get; set; }
    }
}
