//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIUTAttendance.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int SeminarID { get; set; }
        public int TutorID { get; set; }
        public int StudentID { get; set; }
        public string Status { get; set; }
        public int TeachingWeek { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Rescheduled { get; set; }
    
        public virtual Seminar Seminar { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
