//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIUTAttendance.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleType
    {
        public int ModuleID { get; set; }
        public int CourseID { get; set; }
        public string Type { get; set; }
        public Nullable<int> Level { get; set; }
        public string DeliveredPeriod { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Module Module { get; set; }
    }
}
