//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIUTAttendance.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminar
    {
        public Seminar()
        {
            this.Attendances = new HashSet<Attendance>();
            this.SeminarReschedules = new HashSet<SeminarReschedule>();
            this.Groups = new HashSet<Group>();
        }
    
        public int ID { get; set; }
        public int ModuleID { get; set; }
        public int TimeID { get; set; }
        public int TutorID { get; set; }
        public string DayOfWeek { get; set; }
        public string StartTime { get; set; }
        public string Building { get; set; }
        public string Room { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Module Module { get; set; }
        public virtual Time Time { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ICollection<SeminarReschedule> SeminarReschedules { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
