//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIUTAttendance.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public Time()
        {
            this.CourseRegistrations = new HashSet<CourseRegistration>();
            this.CourseRegistrations1 = new HashSet<CourseRegistration>();
            this.GroupAllocations = new HashSet<GroupAllocation>();
            this.Groups = new HashSet<Group>();
            this.LevelProgressions = new HashSet<LevelProgression>();
            this.ModuleRegistrations = new HashSet<ModuleRegistration>();
            this.ModuleTutors = new HashSet<ModuleTutor>();
            this.Seminars = new HashSet<Seminar>();
        }
    
        public int ID { get; set; }
        public string AcademicYear { get; set; }
        public string Period { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<CourseRegistration> CourseRegistrations { get; set; }
        public virtual ICollection<CourseRegistration> CourseRegistrations1 { get; set; }
        public virtual ICollection<GroupAllocation> GroupAllocations { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<LevelProgression> LevelProgressions { get; set; }
        public virtual ICollection<ModuleRegistration> ModuleRegistrations { get; set; }
        public virtual ICollection<ModuleTutor> ModuleTutors { get; set; }
        public virtual ICollection<Seminar> Seminars { get; set; }
    }
}
